extends Node

const ROASTS := [
    {"emoji": "😱", "text": "Even my Grandmother is faster!"},
    {"emoji": "😴", "text": "Bro fell asleep at the paddle."},
    {"emoji": "🐢", "text": "Your reflexes are slower than a Windows update."},
    {"emoji": "👻", "text": "Did you even see the ball, or just hear it go past?"},
    {"emoji": "🤡", "text": "Bold strategy. Terrible execution."},
    {"emoji": "🪦", "text": "That miss had energy. Wrong energy, but energy."},
    {"emoji": "🦴", "text": "The paddle is crying. I can hear it."},
    {"emoji": "💀", "text": "That was embarrassing. For both of us."},
    {"emoji": "🐌", "text": "I've seen toasters with better reaction times."},
    {"emoji": "🎪", "text": "At this point the paddle is just decoration."},
    {"emoji": "🤦", "text": "You're not losing, you're just winning in reverse."},
    {"emoji": "🔮", "text": "Lag? No, that's just you."},
    {"emoji": "🫠", "text": "Impressive – you actually get worse over time."},
    {"emoji": "🧊", "text": "You move like the ball has a restraining order on you."},
    {"emoji": "🎭", "text": "Is this your first time seeing a screen?"},
    {"emoji": "⚰️", "text": "The ball wasn't even trying and you still missed."},
    {"emoji": "🦽", "text": "Bro needs a GPS to find the ball."},
    {"emoji": "🫥", "text": "You were there. The paddle was there. Magic didn't happen."},
    {"emoji": "🧟", "text": "Playing dead is a strategy. Not a good one, but sure."},
    {"emoji": "🪆", "text": "Your reaction time has a reaction time."},
    {"emoji": "🎯", "text": "Aim: nowhere. Result: checks out."},
    {"emoji": "🧸", "text": "Even a stuffed animal puts up more resistance."},
    {"emoji": "🌀", "text": "You're not confused. You're just permanently behind."},
    {"emoji": "🪰", "text": "Flies have better reflexes. And they don't have hands."},
    {"emoji": "🏚️", "text": "Your defense is in ruins. Literally."},
    {"emoji": "🔋", "text": "Running on empty. And it shows."},
    {"emoji": "📉", "text": "Your performance chart goes one direction."},
    {"emoji": "🧯", "text": "No fire here. Just disappointment."},
    {"emoji": "🪣", "text": "You brought a bucket to a laser fight."},
    {"emoji": "🎻", "text": "Play me a sad song. Oh wait, you just did."},
    {"emoji": "🪑", "text": "The chair is more involved than you are."},
    {"emoji": "🌧️", "text": "It's raining Ls and you brought no umbrella."},
    {"emoji": "🧻", "text": "Soft. Disposable. Easily replaced."},
    {"emoji": "📦", "text": "You've been packed up and sent home."},
    {"emoji": "🫧", "text": "Your game plan popped like a bubble."},
]

const COUNTERS := [
    {"emoji": "😤", "text": "At least I have hands."},
    {"emoji": "🙄", "text": "Lucky shot. Enjoy it."},
    {"emoji": "😎", "text": "I was warming up. Now I'm ready."},
    {"emoji": "🫵", "text": "Talk when you actually win."},
    {"emoji": "💅", "text": "Not even worth a response. But here we are."},
    {"emoji": "🥱", "text": "Is that the best you've got?"},
    {"emoji": "😂", "text": "One point and you think you're something."},
    {"emoji": "🔥", "text": "Keep talking. It won't help."},
    {"emoji": "👑", "text": "Temporary. Very temporary."},
    {"emoji": "🫀", "text": "My grandma hits harder. And she's gone."},
    {"emoji": "😇", "text": "Bless your heart."},
    {"emoji": "🤏", "text": "That was a tiny win for a tiny person."},
    {"emoji": "🧠", "text": "I'll store this moment in the bin where it belongs."},
    {"emoji": "⏳", "text": "Your time will run out. Soon."},
    {"emoji": "🪃", "text": "That point is coming back to me. Watch."},
    {"emoji": "🫶", "text": "Good for you. Really. No seriously."},
    {"emoji": "🗑️", "text": "Filing that under: irrelevant."},
    {"emoji": "🧂", "text": "Salty about it? No. Focused. Very focused."},
    {"emoji": "🎖️", "text": "Congratulations on your participation trophy."},
    {"emoji": "📌", "text": "Noted. And immediately forgotten."},
    {"emoji": "🌊", "text": "Enjoy the wave. I'm the tide."},
    {"emoji": "🎲", "text": "Even luck has limits. Yours especially."},
    {"emoji": "🧩", "text": "You're missing a piece. Several, actually."},
    {"emoji": "🪤", "text": "Walked right into that one, didn't you."},
]